"
" ~/.vim/gvimrc
"

" a comma separated list of fonts which will be used
set guifont=Monospace\ 14

" bring up a font requester, where you can pick the font you want
" :set guifont=*

" return the currently used font
" :set guifont?

" describes what components and options of the gui should be used
set guioptions-=T
